apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ required "values.appName must be set" .Values.appName }}
labels:
  app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ required "values.image must be set" .Values.image }}
          ports:
            - containerPort: {{ required "values.port must be set" .Values.port | int }}

          readinessProbe:
            httpGet:
              path: {{ default "/healthz" .Values.readinessProbe.path }}
              port: {{ .Values.port | int }}
            initialDelaySeconds: {{ default 2  .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds:       {{ default 5  .Values.readinessProbe.periodSeconds }}
            timeoutSeconds:      {{ default 1  .Values.readinessProbe.timeoutSeconds }}
            successThreshold:    {{ default 1  .Values.readinessProbe.successThreshold }}
            failureThreshold:    {{ default 3  .Values.readinessProbe.failureThreshold }}

          # Liveness: same endpoint, but more tolerant to let Pod be NotReady first
          livenessProbe:
            httpGet:
              path: {{ default (default "/healthz" .Values.readinessProbe.path) .Values.livenessProbe.path }}
              port: {{ .Values.port | int }}
            initialDelaySeconds: {{ default 5  .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds:       {{ default 5  .Values.livenessProbe.periodSeconds }}
            timeoutSeconds:      {{ default 1  .Values.livenessProbe.timeoutSeconds }}
            failureThreshold:    {{ default 6  .Values.livenessProbe.failureThreshold }}
