apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "generic-service.fullname" . }}-sm
  namespace: {{ .Release.Namespace }}
  labels:
    thmanyah.com/monitor: "true"
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
