apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-sm" (required "values.appName must be set" .Values.appName) }}
  namespace: {{ .Release.Namespace }}
  labels:
    thmanyah.com/monitor: "true"
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s