{{- if .Values.enableVPA }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ printf "%s-vpa" (required "values.appName must be set" .Values.appName) }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | quote }}
  {{- with .Values.vpa.controlledResources }}
  controlledResources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Values.appName }}
        {{- with .Values.vpa.minAllowed }}
        minAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.vpa.maxAllowed }}
        maxAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
