appName: "thmanyah-store"
image: ""
port: 8082

enableHPA: true
enableVPA: true

hpa:
  minReplicas: 3
  maxReplicas: 10

  # Built-in resource metrics (toggle on/off)
  metrics:
    cpu:
      enabled: true
      targetAverageUtilization: 70

vpa:
  updateMode: "Initial"
  minAllowed:
    cpu: "50m"
    memory: "64Mi"
  maxAllowed:
    cpu: "2"
    memory: "2Gi"
